

spring:
  datasource:
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./library;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS LIBRARY
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2